BUZZER_ALARM_TOPIC = "buzzer-alarm"
BUZZER_CLOCK_TOPIC = "buzzer-clock"
B4SD_CLOCK_TOPIC = "b4sd-clock"
ALARM_ACTIVATION_TOPIC = "alarm-activation"
RGB_TOPIC = "rgb"
DOOR_LIGHT_TOPIC = "dl"
DMS_PIN_REQUEST_TOPIC = "dms-pin-request"